### PR TITLE
Issue 5 nibs

### LINKED ISSUE #5: `awakeFromNib` Not Properly Handling Multiple Calls
`BaseView` does not properly handle `awakeFromNib` potentially being called more than once. This could lead to crashes by or strange side effects from repeated setup of subviews.
- [Apple Documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/NSObject_UIKitAdditions/#//apple_ref/occ/instm/NSObject/awakeFromNib)
- [StackOverflow Examples](http://stackoverflow.com/questions/11585956/why-is-awakefromnib-being-called-twice-when-loading-nib-in-nib)

### PR DESCRIPTION
**Pull request by madhikarma**
Fixes #5 
### Description
- Added `isSetup` flag and checking against it before executing setup routines within `awakeFromNib` since it might be called multiple times. 
### Status
- [x] Code review
- [x] Manual testing

cc @aamctustwo @danieladias

### CODE REVIEW

**Comment by ghost** [comment]
@madhikarma We should probably mark `isSetup = true` at the end of `init(frame:)`. Even though it's obvious, it makes the `isSetup` property consistent no matter how you use `BaseView.swift`.

**Comment by madhikarma** [comment]
Done, worth another look @aamctustwo. Q. Do we want #4 to go in first?

**Comment by ghost** [comment]
@madhikarma Let's do #4 first since it includes complete unit test coverage, which would be useful before we bring in any other PR's.

**Comment by ghost** [comment]
@madhikarma the `isSetup` looks much better now!

**Comment by madhikarma** [comment]
Unit tests added

**Pull request merged**
