### PR TITLE
Issue 11 - Conflicting constraints

### PR DESCRIPTION
**Pull request by markuspersson**
Resolves issue #11 
### Description
- Opted-out of system constraints by setting `translatesAutoresizingMaskIntoConstraints = false`
- Removed unnecessary unwrap of a non-optional value
### Status
- [x] Code review
- [x] Manual testing

cc @madhikarma

### CODE REVIEW

**Comment by markuspersson** [comment]
No idea why the CI would fail. The log says:

```
Test target BaseViewTests encountered an error (The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 4.)
```

The tests runs fine locally so maybe just a CI hick-up?

**Comment by madhikarma** [comment]
Yeah sometimes it can happen on Travis CI. I restarted the job and tests now pass there and still locally as well. :tada:

**Comment by madhikarma** [comment]
Code looks fine :+1: Thanks for fixing this @markuspersson! Looks like a nice way for us to collaborate further across studios 

@aamctustwo want to take a look as well?

**Comment by madhikarma** [comment]
Tested with success
- No signs of regression
- No errors emitted in the console log when running the sample project

**Comment by madhikarma** [comment]
:ship:

**Comment by ghost** [comment]
These should be updated in the README example as well.

**Comment by madhikarma** [comment]
What did you want to update in the README @aamctustwo? 

To match the code in `View.swift` exactly line for line? (the README example does set `translatesAutoresizingMaskIntoConstraints` to false)

**Comment by ghost** [comment]
@madhikarma Yes. Have the examples in the README match the example iOS app in the source.

**Comment by madhikarma** [comment]
Ok take a look at the changes I made to the README @aamctustwo (whilst waiting for the green :traffic_light: from Travis CI)

**Comment by ghost** [comment]
@madhikarma :ship: when Travis turns green.

**Pull request merged**
